# Generated by Django 4.2.6 on 2023-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appautenticacion', '0006_alter_customuser_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correo',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
