# Generated by Django 4.2.6 on 2023-12-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appautenticacion', '0007_customuser_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='correo',
        ),
    ]
