# Generated by Django 4.2.6 on 2023-12-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstituciones', '0012_alter_mantenimientocorrectivo_tipo_gasto_correctivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientocorrectivo',
            name='descripcion_compra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mantenimientocorrectivo',
            name='servicio_salud',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mantenimientocorrectivo',
            name='tipo_gasto_correctivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
